### ISSUE TITLE
Consider a database of NT plugins

### ISSUE THREAD

**Issue by Xunie** [Rainyan/sourcemod-nt-spectator-lasers#1]
Hey, lewd plugin.

Have you considered making a database of plugins on github? Something that can link to all repositories of NT-related plugins?

(Can't reach you on Steam, figured I'd make a github issue, lol)

**Comment by Rainyan** [comment]
I've created a utility that should help make _"Community Recommended Plugins"_ lists a reality:

https://github.com/CreamySoup/soup

More deets in the url readme.

While the "_soup_" tool itself should already work, as of writing this comment it is still missing some well crafted recommendation lists.

Regardless, I'm gonna close this one, since the linked project _should_ hopefully be addressing this exact problem some time in the near future!
